[workspace]
members = ["foobar-web", "foobar-daemon", "foobar-common"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.95"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }

[workspace.lints.clippy]
#insta.opt-level = 3
